### ISSUE TITLE
Task 7.1 Create three ”company databases” on MongoDB

### ISSUE THREAD

**Issue by elliot-eriksson** [elliot-eriksson/Digital-Product-Passports-DPPs-federated-system#35]
Related to user story #15

**Comment by SuneLarsson** [comment]
Three databases are created on MongoDB

**Comment by AlbinMartensson** [comment]
The three databases on MongoDB is created and works.

**Comment by elliot-eriksson** [comment]
![Image](https://github.com/elliot-eriksson/Digital-Product-Passports-DPPs-federated-system/assets/31346115/87b8f65e-3825-4d07-930b-a7c32891a2b6)
