### ISSUE TITLE
Task 7.2 Set up 4 different rolls for access rights (One for Owning company, admin, remanufacture (car mechanic) and user.

### ISSUE THREAD

**Issue by elliot-eriksson** [elliot-eriksson/Digital-Product-Passports-DPPs-federated-system#36]
Related to user story #15

**Comment by SuneLarsson** [comment]
4 rolls are created

**Comment by elliot-eriksson** [comment]
![Image](https://github.com/elliot-eriksson/Digital-Product-Passports-DPPs-federated-system/assets/31346115/f53f206e-797a-456f-9a40-900bd94cdb7e)

**Comment by AlbinMartensson** [comment]
We changed it from 4 rolls to 3 rolls instead, but except from that it works fine.
